name = "ideation-engine"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
[[kv_namespaces]]
binding = "IDEATE_KV"
id = "5260eba49774462eabe9f0d8603b2ade"
